services:
  auth_service:
    build: ./src/auth-service
    container_name: auth_service
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_NAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      AUTH_TABLE_NAME: ${AUTH_TABLE_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      app_network:
        ipv4_address: 172.28.0.10
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      app_network:
        ipv4_address: 172.28.0.21
networks:
  app_network:
    driver: bridge
    name: mp4mp3_network
    ipam:
      config:
        - subnet: 172.28.0.0/16
volumes:
  pg_data:
