services:
  auth_service:
    build: ./src/auth-service
    container_name: auth_service
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_NAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      AUTH_TABLE_NAME: ${AUTH_TABLE_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      app_network:
        ipv4_address: 172.28.0.10
  converter-service:
    build: ./src/converter-service
    container_name: converter_service
    restart: always
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      RABBITMQ_HOST: rabbit-mq
      RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
      - rabbit-mq
    networks:
      app_network:
        ipv4_address: 172.28.0.14
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      app_network:
        ipv4_address: 172.28.0.11
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo_data:/data/db
    networks:
      app_network:
        ipv4_address: 172.28.0.12
  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      app_network:
        ipv4_address: 172.28.0.13
networks:
  app_network:
    driver: bridge
    name: mp4mp3_network
    ipam:
      config:
        - subnet: 172.28.0.0/16
volumes:
  pg_data:
  mongo_data:
